In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("used_phone_price_prediction_cleaned.csv")

In [4]:
df.head(5)

,brand,release_year,ram_gb,storage_gb,screen_size_inches,battery_capacity,camera_score,os_type,has_5g,original_price,...,screen_cracked,body_damage,repair_history,water_damage,city_tier,seller_type,warranty_remaining_months,box_available,charger_available,resale_price
0,0,2025,4,256,6.93,4130,100,0,1,147337,...,0,0,0,0,0,0,11,1,1,47891.46
1,1,2024,16,64,6.29,5558,67,0,1,75725,...,0,0,0,0,2,1,8,1,0,17663.21
2,2,2022,4,128,5.52,5945,67,1,1,134358,...,0,0,0,0,0,0,0,0,1,67268.20
3,3,2024,16,512,5.99,5767,57,0,1,96807,...,0,0,0,1,0,1,11,1,1,12626.26
4,3,2021,4,128,6.59,5336,44,0,1,74505,...,0,0,0,0,2,1,24,1,1,20662.25

In [6]:
df.shape

(1000000, 25)

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 25 columns):
 #   Column                     Non-Null Count    Dtype
---  ------                     --------------    -----
 0   brand                      1000000 non-null  int64
 1   release_year               1000000 non-null  int64
 2   ram_gb                     1000000 non-null  int64
 3   storage_gb                 1000000 non-null  int64
 4   screen_size_inches         1000000 non-null  float64
 5   battery_capacity           1000000 non-null  int64
 6   camera_score               1000000 non-null  int64
 7   os_type                    1000000 non-null  int64
 8   has_5g                     1000000 non-null  int64
 9   original_price             1000000 non-null  int64
 10  purchase_year              1000000 non-null  int64
 11  age_months                 1000000 non-null  int64
 12  usage_hours_per_day        1000000 non-null  float64
 13  condition                  1000000 non-null  int64
 14  battery_health             1000000 non-null  int64
 15  screen_cracked             1000000 non-null  int64
 16  body_damage                1000000 non-null  int64
 17  repair_history             1000000 non-null  int64
 18  water_damage               1000000 non-null  int64
 19  city_tier                  1000000 non-null  int64
 20  seller_type                1000000 non-null  int64
 21  warranty_remaining_months  1000000 non-null  int64
 22  box_available              1000000 non-null  int64
 23  charger_available          1000000 non-null  int64
 24  resale_price               1000000 non-null  float64
dtypes: float64(3), int64(22)
memory usage: 190.7 MB

In [8]:
df.describe()

,brand,release_year,ram_gb,storage_gb,screen_size_inches,battery_capacity,camera_score,os_type,has_5g,original_price,...,screen_cracked,body_damage,repair_history,water_damage,city_tier,seller_type,warranty_remaining_months,box_available,charger_available,resale_price
count,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.00000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,...,1000000.000000,1000000.000000,1000000.00000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000
mean,3.002193,2022.001836,9.201878,396.798912,6.25037,4750.004425,69.980058,0.142690,0.800063,79966.195735,...,0.079978,0.119653,0.15053,0.030106,0.999116,0.499737,8.099701,0.699651,0.849771,22597.996211
std,1.999934,2.001558,4.309755,349.401760,0.43290,1009.971322,17.607651,0.349757,0.399953,40413.479880,...,0.271259,0.324555,0.35759,0.170879,0.816232,0.500000,8.158009,0.458410,0.357296,16652.621181
min,0.000000,2019.000000,4.000000,64.000000,5.50000,3000.000000,40.000000,0.000000,0.000000,10000.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2000.000000
25%,1.000000,2020.000000,6.000000,128.000000,5.88000,3877.000000,55.000000,0.000000,1.000000,45028.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,10365.927500
50%,3.000000,2022.000000,8.000000,256.000000,6.25000,4750.000000,70.000000,0.000000,1.000000,79947.000000,...,0.000000,0.000000,0.00000,0.000000,1.000000,0.000000,6.000000,1.000000,1.000000,18555.195000
75%,5.000000,2024.000000,12.000000,512.000000,6.63000,5623.000000,85.000000,0.000000,1.000000,114984.000000,...,0.000000,0.000000,0.00000,0.000000,2.000000,1.000000,15.000000,1.000000,1.000000,30427.912500
max,6.000000,2025.000000,16.000000,1024.000000,7.00000,6500.000000,100.000000,1.000000,1.000000,150000.000000,...,1.000000,1.000000,1.00000,1.000000,2.000000,1.000000,24.000000,1.000000,1.000000,160257.480000

In [9]:
df_ndarray = df.to_numpy()

In [10]:
df_ndarray

array([[0.000000e+00, 2.025000e+03, 4.000000e+00, ..., 1.000000e+00,
        1.000000e+00, 4.789146e+04],
       [1.000000e+00, 2.024000e+03, 1.600000e+01, ..., 1.000000e+00,
        0.000000e+00, 1.766321e+04],
       [2.000000e+00, 2.022000e+03, 4.000000e+00, ..., 0.000000e+00,
        1.000000e+00, 6.726820e+04],
       ...,
       [2.000000e+00, 2.022000e+03, 4.000000e+00, ..., 0.000000e+00,
        1.000000e+00, 3.123616e+04],
       [2.000000e+00, 2.023000e+03, 1.200000e+01, ..., 1.000000e+00,
        1.000000e+00, 1.628820e+04],
       [0.000000e+00, 2.020000e+03, 1.600000e+01, ..., 1.000000e+00,
        1.000000e+00, 9.819030e+03]], shape=(1000000, 25))

In [18]:
df_ndarray[0].sum()

np.float64(203922.09)

In [19]:
df_ndarray.shape

(1000000, 25)

In [20]:
df_ndarray.size

25000000

In [21]:
df_ndarray.dtype

dtype('float64')

In [26]:
type(df_ndarray)

numpy.ndarray

In [23]:
df_ndarray.ndim

2

In [24]:
df_ndarray = df.to_numpy()

In [28]:
df_ndarray[6]

array([2.00000e+00, 2.02500e+03, 4.00000e+00, 2.56000e+02, 5.80000e+00,
       5.57200e+03, 4.60000e+01, 1.00000e+00, 1.00000e+00, 1.27845e+05,
       2.02500e+03, 4.30000e+01, 1.07000e+01, 1.00000e+00, 6.00000e+01,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 1.00000e+00,
       1.00000e+00, 1.50000e+01, 1.00000e+00, 1.00000e+00, 1.58630e+04])

In [29]:
ram = df_ndarray[:, 2]

In [30]:
ram

array([ 4., 16.,  4., ...,  4., 12., 16.], shape=(1000000,))

In [31]:
year = df_ndarray[:, 1]
year

array([2025., 2024., 2022., ..., 2022., 2023., 2020.], shape=(1000000,))

In [32]:
type(year)

numpy.ndarray

In [33]:
year.max()

np.float64(2025.0)

In [34]:
year.min()

np.float64(2019.0)

In [35]:
## Normalization of data
battery = df_ndarray[:,5]

normalized = (battery - np.mean(battery)) / np.std(battery)

In [41]:
normalized[0:100]

array([-0.61388351,  0.80001873,  1.18319812,  1.00695541,  0.5802104 ,
        1.52380202,  0.81388052, -0.26832897,  0.40594794,  1.03863949,
        0.76239389, -1.48222543,  1.34062841, -1.71688567, -1.60698151,
       -1.21390084,  0.44258266, -0.61487363,  1.54261445, -0.11386906,
       -0.8465635 ,  1.25448731,  0.38911577, -0.35645032,  1.31686535,
        0.12970234, -0.60398223,  1.25547744,  0.28317212, -1.6713398 ,
        0.74655184, -0.49308794,  0.37426386,  1.50102909,  0.08514659,
        1.52182177, -1.60896176, -0.86537592,  0.00494626, -1.416877  ,
        1.19606978,  0.29901416,  0.39703679, -1.22182186,  0.08316634,
        1.41290773, -0.80695839,  0.23762625, -0.7534915 , -0.94161575,
        1.29112203,  0.18712974, -1.60698151,  1.32478637,  1.30399369,
        0.01187715,  1.15151404, -0.1871385 , -0.28120063,  1.4762759 ,
        0.2970339 , -0.15446429, -0.15248403,  1.43073003,  1.45350296,
        0.25940905,  0.33069824,  1.34062841,  1.13468187,  0.7198184 ,
        0.12376157,  1.72875844,  0.19703101, -1.62381368,  1.66043964,
        0.31782658, -0.45447296,  1.45152271,  1.66539027,  1.08319523,
        1.48419692,  0.40693807, -0.6317058 , -0.30694394, -1.43271905,
        0.78318657, -1.29311105, -1.02082596,  1.09111625, -0.14555314,
        1.53568356,  0.34852054,  1.07032357,  1.40795709,  1.51192049,
        1.47924628, -1.09805591,  1.37033224,  0.15940617,  0.84259422])

In [37]:
normalized.shape

(1000000,)

In [46]:
# Phones with RAM greater than 8 GB
high_ram = df_ndarray[df_ndarray[:, 2] > 8]
high_ram[0:5]

array([[1.000000e+00, 2.024000e+03, 1.600000e+01, 6.400000e+01,
        6.290000e+00, 5.558000e+03, 6.700000e+01, 0.000000e+00,
        1.000000e+00, 7.572500e+04, 2.024000e+03, 4.900000e+01,
        2.000000e+00, 1.000000e+00, 9.800000e+01, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 0.000000e+00, 2.000000e+00,
        1.000000e+00, 8.000000e+00, 1.000000e+00, 0.000000e+00,
        1.766321e+04],
       [3.000000e+00, 2.024000e+03, 1.600000e+01, 5.120000e+02,
        5.990000e+00, 5.767000e+03, 5.700000e+01, 0.000000e+00,
        1.000000e+00, 9.680700e+04, 2.024000e+03, 6.200000e+01,
        4.900000e+00, 2.000000e+00, 9.900000e+01, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 1.000000e+00, 0.000000e+00,
        1.000000e+00, 1.100000e+01, 1.000000e+00, 1.000000e+00,
        1.262626e+04],
       [5.000000e+00, 2.022000e+03, 1.200000e+01, 1.024000e+03,
        5.510000e+00, 4.479000e+03, 4.800000e+01, 0.000000e+00,
        1.000000e+00, 2.354500e+04, 2.022000e+03, 3.000000e+00,
        4.700000e+00, 3.000000e+00, 8.600000e+01, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 1.000000e+00, 0.000000e+00,
        1.000000e+00, 0.000000e+00, 0.000000e+00, 1.000000e+00,
        2.282300e+03],
       [5.000000e+00, 2.020000e+03, 1.200000e+01, 2.560000e+02,
        6.800000e+00, 3.524000e+03, 9.700000e+01, 0.000000e+00,
        0.000000e+00, 1.206270e+05, 2.021000e+03, 5.000000e+01,
        9.800000e+00, 1.000000e+00, 1.000000e+02, 0.000000e+00,
        1.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 1.000000e+00, 1.000000e+00,
        3.429465e+04],
       [6.000000e+00, 2.022000e+03, 1.200000e+01, 1.280000e+02,
        6.950000e+00, 4.129000e+03, 5.800000e+01, 0.000000e+00,
        1.000000e+00, 9.275000e+04, 2.025000e+03, 1.300000e+01,
        5.800000e+00, 1.000000e+00, 8.000000e+01, 0.000000e+00,
        1.000000e+00, 0.000000e+00, 0.000000e+00, 1.000000e+00,
        0.000000e+00, 0.000000e+00, 0.000000e+00, 1.000000e+00,
        2.815240e+04]])

In [47]:
## Phones with storage equal to 256
phones = df_ndarray[df_ndarray[:, 3] == 256]
phones[0:5]

array([[0.000000e+00, 2.025000e+03, 4.000000e+00, 2.560000e+02,
        6.930000e+00, 4.130000e+03, 1.000000e+02, 0.000000e+00,
        1.000000e+00, 1.473370e+05, 2.025000e+03, 5.200000e+01,
        2.700000e+00, 0.000000e+00, 7.800000e+01, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 1.100000e+01, 1.000000e+00, 1.000000e+00,
        4.789146e+04],
       [2.000000e+00, 2.025000e+03, 4.000000e+00, 2.560000e+02,
        5.800000e+00, 5.572000e+03, 4.600000e+01, 1.000000e+00,
        1.000000e+00, 1.278450e+05, 2.025000e+03, 4.300000e+01,
        1.070000e+01, 1.000000e+00, 6.000000e+01, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 0.000000e+00, 1.000000e+00,
        1.000000e+00, 1.500000e+01, 1.000000e+00, 1.000000e+00,
        1.586300e+04],
       [0.000000e+00, 2.021000e+03, 6.000000e+00, 2.560000e+02,
        6.850000e+00, 3.253000e+03, 8.700000e+01, 0.000000e+00,
        0.000000e+00, 1.432720e+05, 2.021000e+03, 3.600000e+01,
        1.100000e+00, 0.000000e+00, 7.200000e+01, 0.000000e+00,
        0.000000e+00, 1.000000e+00, 0.000000e+00, 1.000000e+00,
        0.000000e+00, 0.000000e+00, 0.000000e+00, 1.000000e+00,
        3.188906e+04],
       [5.000000e+00, 2.020000e+03, 1.200000e+01, 2.560000e+02,
        6.800000e+00, 3.524000e+03, 9.700000e+01, 0.000000e+00,
        0.000000e+00, 1.206270e+05, 2.021000e+03, 5.000000e+01,
        9.800000e+00, 1.000000e+00, 1.000000e+02, 0.000000e+00,
        1.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 1.000000e+00, 1.000000e+00,
        3.429465e+04],
       [3.000000e+00, 2.019000e+03, 1.600000e+01, 2.560000e+02,
        6.060000e+00, 5.143000e+03, 6.200000e+01, 0.000000e+00,
        1.000000e+00, 7.147600e+04, 2.021000e+03, 3.600000e+01,
        3.600000e+00, 1.000000e+00, 7.700000e+01, 0.000000e+00,
        0.000000e+00, 1.000000e+00, 0.000000e+00, 2.000000e+00,
        0.000000e+00, 1.200000e+01, 1.000000e+00, 1.000000e+00,
        2.177249e+04]])

In [ ]:
## A Common workflow is:

# 1. Read data
df = pd.read_csv("phones.csv")

# 2. Clean data
# ...

# 3. Encode categorical columns
# ...

# 4. Split features and target
X = df.drop("original_price", axis=1).to_numpy()
y = df["original_price"].to_numpy()

# 5. Use NumPy for numerical operations
X = (X - np.mean(X, axis=0)) / np.std(X, axis=0)

# 6. Train an ML model