In [5]:
import pandas as pd
import numpy as np

df = pd.read_csv("sales_data.csv")
# print(df)

In [6]:
df

,Transaction_ID,Date,Product,Category,Units_Sold,Unit_Price,Region
0,101,2026-07-01,Laptop,Electronics,1.0,1200,North
1,102,2026-07-01,Mouse,Accessories,4.0,25,East
2,103,2026-07-02,Monitor,Electronics,2.0,300,West
3,104,2026-07-02,Laptop,Electronics,1.0,1200,South
4,105,2026-07-03,Mouse,Accessories,5.0,25,East
5,106,2026-07-03,Keyboard,Accessories,2.0,50,North
6,107,2026-07-04,Monitor,Electronics,NaN,300,West
7,108,2026-07-04,Laptop,Electronics,3.0,1200,North
8,109,2026-07-05,Mouse,Accessories,10.0,25,South
9,110,2026-07-05,Unknown,Accessories,1.0,45,East

In [7]:
## Selecting specific columns
df["Category"].head(5)  # Selecting the 'Category' column and displaying the first 5 rows

0    Electronics
1    Accessories
2    Electronics
3    Electronics
4    Accessories
Name: Category, dtype: str

In [8]:
west_sold_products = df[df["Region"] == "West"]["Product"] # Filtering for 'West' region and selecting 'Product' column
west_sold_products

2    Monitor
6    Monitor
Name: Product, dtype: str

In [12]:
accessories_mouse = df[(df["Category"] == "Accessories") & (df["Product"] == "Mouse")]  # Filtering for 'Accessories' category and selecting 'Product' column
accessories_mouse

,Transaction_ID,Date,Product,Category,Units_Sold,Unit_Price,Region
1,102,2026-07-01,Mouse,Accessories,4.0,25,East
4,105,2026-07-03,Mouse,Accessories,5.0,25,East
8,109,2026-07-05,Mouse,Accessories,10.0,25,South

In [13]:
accessories_keyboard = df[(df["Category"] == "Accessories") & (df["Product"] == "Keyboard")]  # Filtering for 'Accessories' category and selecting 'Product' column
accessories_keyboard

,Transaction_ID,Date,Product,Category,Units_Sold,Unit_Price,Region
5,106,2026-07-03,Keyboard,Accessories,2.0,50,North