In [51]:
import pandas as pd

## Cleaning a DataSet with 1Million Rows
- **Removing Duplicates**
- **Identifying Outliers**
- **Find And Removing/Filling Missing Values**
- **Removing Unwanted Colunms: `Feature Engineering`**
- **Data Standarisation**
- **Encoding**
- **Converting Data In Numerical Values For ML Model**

In [52]:
df = pd.read_csv("used_phone_price_prediction_1M.csv")

In [53]:
df.shape # Display the shape of the DataFrame (rows, columns)

(1000000, 28)

In [54]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 28 columns):
 #   Column                     Non-Null Count    Dtype
---  ------                     --------------    -----
 0   brand                      1000000 non-null  str
 1   model                      1000000 non-null  str
 2   release_year               1000000 non-null  int64
 3   ram_gb                     1000000 non-null  int64
 4   storage_gb                 1000000 non-null  int64
 5   screen_size_inches         1000000 non-null  float64
 6   battery_capacity           1000000 non-null  int64
 7   processor_score            1000000 non-null  int64
 8   camera_score               1000000 non-null  int64
 9   os_type                    1000000 non-null  str
 10  has_5g                     1000000 non-null  int64
 11  original_price             1000000 non-null  int64
 12  purchase_year              1000000 non-null  int64
 13  age_months                 1000000 non-null  int64
 14  usage_hours_per_day        1000000 non-null  float64
 15  condition                  1000000 non-null  str
 16  battery_health             1000000 non-null  int64
 17  screen_cracked             1000000 non-null  int64
 18  body_damage                1000000 non-null  int64
 19  repair_history             1000000 non-null  int64
 20  water_damage               1000000 non-null  int64
 21  city_tier                  1000000 non-null  str
 22  seller_type                1000000 non-null  str
 23  warranty_remaining_months  1000000 non-null  int64
 24  box_available              1000000 non-null  int64
 25  charger_available          1000000 non-null  int64
 26  market_demand_score        1000000 non-null  int64
 27  resale_price               1000000 non-null  float64
dtypes: float64(3), int64(19), str(6)
memory usage: 213.6 MB

In [55]:
df.describe() # Display summary statistics for numerical columns in the DataFrame

,release_year,ram_gb,storage_gb,screen_size_inches,battery_capacity,processor_score,camera_score,has_5g,original_price,purchase_year,...,battery_health,screen_cracked,body_damage,repair_history,water_damage,warranty_remaining_months,box_available,charger_available,market_demand_score,resale_price
count,1000000.000000,1000000.000000,1000000.000000,1000000.00000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,...,1000000.000000,1000000.000000,1000000.000000,1000000.00000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000
mean,2022.001836,9.201878,396.798912,6.25037,4750.004425,70.018905,69.980058,0.800063,79966.195735,2023.501257,...,77.507898,0.079978,0.119653,0.15053,0.030106,8.099701,0.699651,0.849771,70.020885,22597.996211
std,2.001558,4.309755,349.401760,0.43290,1009.971322,17.600272,17.607651,0.399953,40413.479880,1.607323,...,13.272198,0.271259,0.324555,0.35759,0.170879,8.158009,0.458410,0.357296,17.618549,16652.621181
min,2019.000000,4.000000,64.000000,5.50000,3000.000000,40.000000,40.000000,0.000000,10000.000000,2019.000000,...,55.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,40.000000,2000.000000
25%,2020.000000,6.000000,128.000000,5.88000,3877.000000,55.000000,55.000000,1.000000,45028.000000,2023.000000,...,66.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,1.000000,55.000000,10365.927500
50%,2022.000000,8.000000,256.000000,6.25000,4750.000000,70.000000,70.000000,1.000000,79947.000000,2024.000000,...,78.000000,0.000000,0.000000,0.00000,0.000000,6.000000,1.000000,1.000000,70.000000,18555.195000
75%,2024.000000,12.000000,512.000000,6.63000,5623.000000,85.000000,85.000000,1.000000,114984.000000,2025.000000,...,89.000000,0.000000,0.000000,0.00000,0.000000,15.000000,1.000000,1.000000,85.000000,30427.912500
max,2025.000000,16.000000,1024.000000,7.00000,6500.000000,100.000000,100.000000,1.000000,150000.000000,2025.000000,...,100.000000,1.000000,1.000000,1.00000,1.000000,24.000000,1.000000,1.000000,100.000000,160257.480000

In [56]:
df.head(5)

,brand,model,release_year,ram_gb,storage_gb,screen_size_inches,battery_capacity,processor_score,camera_score,os_type,...,body_damage,repair_history,water_damage,city_tier,seller_type,warranty_remaining_months,box_available,charger_available,market_demand_score,resale_price
0,Realme,Realme GT,2025,4,256,6.93,4130,47,100,Android,...,0,0,0,Tier1,Individual,11,1,1,99,47891.46
1,Samsung,Galaxy S21,2024,16,64,6.29,5558,81,67,Android,...,0,0,0,Tier3,Store,8,1,0,64,17663.21
2,Apple,iPhone 11,2022,4,128,5.52,5945,59,67,iOS,...,0,0,0,Tier1,Individual,0,0,1,68,67268.20
3,Google,Pixel 6,2024,16,512,5.99,5767,84,57,Android,...,0,0,1,Tier1,Store,11,1,1,50,12626.26
4,Google,Pixel 7,2021,4,128,6.59,5336,98,44,Android,...,0,0,0,Tier3,Store,24,1,1,66,20662.25

In [57]:
df.tail()

,brand,model,release_year,ram_gb,storage_gb,screen_size_inches,battery_capacity,processor_score,camera_score,os_type,...,body_damage,repair_history,water_damage,city_tier,seller_type,warranty_remaining_months,box_available,charger_available,market_demand_score,resale_price
999995,Samsung,Galaxy A54,2023,6,128,6.61,6358,99,63,Android,...,0,0,0,Tier3,Store,11,1,1,95,56194.05
999996,Samsung,Galaxy A54,2021,16,512,6.19,6142,63,43,Android,...,0,0,0,Tier3,Store,11,0,1,65,2040.32
999997,Apple,iPhone 15,2022,4,256,5.97,5874,79,49,iOS,...,0,0,0,Tier2,Individual,14,0,1,99,31236.16
999998,Apple,iPhone 13,2023,12,512,6.73,5220,53,56,iOS,...,0,0,0,Tier3,Store,17,1,1,57,16288.20
999999,Realme,Realme GT,2020,16,256,6.16,6463,91,51,Android,...,0,1,0,Tier2,Individual,10,1,1,83,9819.03

In [58]:
for col in df.columns:  # Display the column names of the DataFrame
    print(col)

brand
model
release_year
ram_gb
storage_gb
screen_size_inches
battery_capacity
processor_score
camera_score
os_type
has_5g
original_price
purchase_year
age_months
usage_hours_per_day
condition
battery_health
screen_cracked
body_damage
repair_history
water_damage
city_tier
seller_type
warranty_remaining_months
box_available
charger_available
market_demand_score
resale_price

In [59]:
## Dropping the columns which are not required for analysis

df = df.drop(columns=["market_demand_score", "processor_score"]) 
df

,brand,model,release_year,ram_gb,storage_gb,screen_size_inches,battery_capacity,camera_score,os_type,has_5g,...,screen_cracked,body_damage,repair_history,water_damage,city_tier,seller_type,warranty_remaining_months,box_available,charger_available,resale_price
0,Realme,Realme GT,2025,4,256,6.93,4130,100,Android,1,...,0,0,0,0,Tier1,Individual,11,1,1,47891.46
1,Samsung,Galaxy S21,2024,16,64,6.29,5558,67,Android,1,...,0,0,0,0,Tier3,Store,8,1,0,17663.21
2,Apple,iPhone 11,2022,4,128,5.52,5945,67,iOS,1,...,0,0,0,0,Tier1,Individual,0,0,1,67268.20
3,Google,Pixel 6,2024,16,512,5.99,5767,57,Android,1,...,0,0,0,1,Tier1,Store,11,1,1,12626.26
4,Google,Pixel 7,2021,4,128,6.59,5336,44,Android,1,...,0,0,0,0,Tier3,Store,24,1,1,20662.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,Samsung,Galaxy A54,2023,6,128,6.61,6358,63,Android,0,...,0,0,0,0,Tier3,Store,11,1,1,56194.05
999996,Samsung,Galaxy A54,2021,16,512,6.19,6142,43,Android,1,...,0,0,0,0,Tier3,Store,11,0,1,2040.32
999997,Apple,iPhone 15,2022,4,256,5.97,5874,49,iOS,1,...,0,0,0,0,Tier2,Individual,14,0,1,31236.16
999998,Apple,iPhone 13,2023,12,512,6.73,5220,56,iOS,1,...,0,0,0,0,Tier3,Store,17,1,1,16288.20
999999,Realme,Realme GT,2020,16,256,6.16,6463,51,Android,1,...,0,0,1,0,Tier2,Individual,10,1,1,9819.03

In [60]:
## Finding Duplicate Rows in the DataFrame

df.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
999995    False
999996    False
999997    False
999998    False
999999    False
Length: 1000000, dtype: bool

In [61]:
df.isnull().sum()  # Count the number of missing values in each column

brand                        0
model                        0
release_year                 0
ram_gb                       0
storage_gb                   0
screen_size_inches           0
battery_capacity             0
camera_score                 0
os_type                      0
has_5g                       0
original_price               0
purchase_year                0
age_months                   0
usage_hours_per_day          0
condition                    0
battery_health               0
screen_cracked               0
body_damage                  0
repair_history               0
water_damage                 0
city_tier                    0
seller_type                  0
warranty_remaining_months    0
box_available                0
charger_available            0
resale_price                 0
dtype: int64

In [62]:
df["brand"].head(5)

0     Realme
1    Samsung
2      Apple
3     Google
4     Google
Name: brand, dtype: str

In [63]:
df["brand"].value_counts()  # Count the occurrences of each unique value in the "brand" column

brand
OnePlus    143120
Xiaomi     143043
Vivo       142991
Google     142795
Samsung    142735
Apple      142690
Realme     142626
Name: count, dtype: int64

In [64]:
df[df["brand"].isnull()]  # Display rows where the "brand" column has missing values

Empty DataFrame
Columns: [brand, model, release_year, ram_gb, storage_gb, screen_size_inches, battery_capacity, camera_score, os_type, has_5g, original_price, purchase_year, age_months, usage_hours_per_day, condition, battery_health, screen_cracked, body_damage, repair_history, water_damage, city_tier, seller_type, warranty_remaining_months, box_available, charger_available, resale_price]
Index: []

[0 rows x 26 columns]

In [65]:
df["brand"].unique()  # Display the unique values in the "brand" column

<StringArray>
['Realme', 'Samsung', 'Apple', 'Google', 'OnePlus', 'Vivo', 'Xiaomi']
Length: 7, dtype: str

In [66]:
df["brand"].dtype  # Display the data type of the "brand" column

In [67]:
## Converting the all categorical columns to lowercase to maintain uniformity

for col in df.columns:
    if df[col].dtype == "str":  # Check if the column is of object type (categorical)
        df[col] = df[col].str.lower()  # Convert the values in the column to lowercase

In [68]:
df.head()

,brand,model,release_year,ram_gb,storage_gb,screen_size_inches,battery_capacity,camera_score,os_type,has_5g,...,screen_cracked,body_damage,repair_history,water_damage,city_tier,seller_type,warranty_remaining_months,box_available,charger_available,resale_price
0,realme,realme gt,2025,4,256,6.93,4130,100,android,1,...,0,0,0,0,tier1,individual,11,1,1,47891.46
1,samsung,galaxy s21,2024,16,64,6.29,5558,67,android,1,...,0,0,0,0,tier3,store,8,1,0,17663.21
2,apple,iphone 11,2022,4,128,5.52,5945,67,ios,1,...,0,0,0,0,tier1,individual,0,0,1,67268.20
3,google,pixel 6,2024,16,512,5.99,5767,57,android,1,...,0,0,0,1,tier1,store,11,1,1,12626.26
4,google,pixel 7,2021,4,128,6.59,5336,44,android,1,...,0,0,0,0,tier3,store,24,1,1,20662.25

In [69]:
df["brand"].unique()

<StringArray>
['realme', 'samsung', 'apple', 'google', 'oneplus', 'vivo', 'xiaomi']
Length: 7, dtype: str

In [70]:
# ['realme', 'samsung', 'apple', 'google', 'oneplus', 'vivo', 'xiaomi']
brand_to_nums = {
    "realme": 0,
    "samsung": 1,
    "apple": 2,
    "google": 3,
    "oneplus": 4,
    "vivo": 5,
    "xiaomi": 6
}

df["brand"] = df["brand"].map(brand_to_nums)  # Map the brand names to numerical values using the dictionary

In [71]:
df["brand"].head(5)

0    0
1    1
2    2
3    3
4    3
Name: brand, dtype: int64

In [72]:
df["brand"].value_counts()  # Count the occurrences of each unique value in the "brand" column

brand
4    143120
6    143043
5    142991
3    142795
1    142735
2    142690
0    142626
Name: count, dtype: int64

In [73]:
df["brand"].unique()  # Display the unique values in the "brand" column after mapping to numerical values

array([0, 1, 2, 3, 4, 5, 6])

In [74]:
df.head()

,brand,model,release_year,ram_gb,storage_gb,screen_size_inches,battery_capacity,camera_score,os_type,has_5g,...,screen_cracked,body_damage,repair_history,water_damage,city_tier,seller_type,warranty_remaining_months,box_available,charger_available,resale_price
0,0,realme gt,2025,4,256,6.93,4130,100,android,1,...,0,0,0,0,tier1,individual,11,1,1,47891.46
1,1,galaxy s21,2024,16,64,6.29,5558,67,android,1,...,0,0,0,0,tier3,store,8,1,0,17663.21
2,2,iphone 11,2022,4,128,5.52,5945,67,ios,1,...,0,0,0,0,tier1,individual,0,0,1,67268.20
3,3,pixel 6,2024,16,512,5.99,5767,57,android,1,...,0,0,0,1,tier1,store,11,1,1,12626.26
4,3,pixel 7,2021,4,128,6.59,5336,44,android,1,...,0,0,0,0,tier3,store,24,1,1,20662.25

In [75]:
# Dropping the model column as it is not required for analysis

df = df.drop(columns=["model"])
df.head(5)

,brand,release_year,ram_gb,storage_gb,screen_size_inches,battery_capacity,camera_score,os_type,has_5g,original_price,...,screen_cracked,body_damage,repair_history,water_damage,city_tier,seller_type,warranty_remaining_months,box_available,charger_available,resale_price
0,0,2025,4,256,6.93,4130,100,android,1,147337,...,0,0,0,0,tier1,individual,11,1,1,47891.46
1,1,2024,16,64,6.29,5558,67,android,1,75725,...,0,0,0,0,tier3,store,8,1,0,17663.21
2,2,2022,4,128,5.52,5945,67,ios,1,134358,...,0,0,0,0,tier1,individual,0,0,1,67268.20
3,3,2024,16,512,5.99,5767,57,android,1,96807,...,0,0,0,1,tier1,store,11,1,1,12626.26
4,3,2021,4,128,6.59,5336,44,android,1,74505,...,0,0,0,0,tier3,store,24,1,1,20662.25

In [76]:
df["os_type"].unique()  # Display the unique values in the "os_type" column

<StringArray>
['android', 'ios']
Length: 2, dtype: str

In [77]:
os_type_to_nums = {
    "android": 0,
    "ios": 1
}

df["os_type"] = df["os_type"].map(os_type_to_nums)  # Map the OS types to numerical values using the dictionary

In [78]:
df.head(5)

,brand,release_year,ram_gb,storage_gb,screen_size_inches,battery_capacity,camera_score,os_type,has_5g,original_price,...,screen_cracked,body_damage,repair_history,water_damage,city_tier,seller_type,warranty_remaining_months,box_available,charger_available,resale_price
0,0,2025,4,256,6.93,4130,100,0,1,147337,...,0,0,0,0,tier1,individual,11,1,1,47891.46
1,1,2024,16,64,6.29,5558,67,0,1,75725,...,0,0,0,0,tier3,store,8,1,0,17663.21
2,2,2022,4,128,5.52,5945,67,1,1,134358,...,0,0,0,0,tier1,individual,0,0,1,67268.20
3,3,2024,16,512,5.99,5767,57,0,1,96807,...,0,0,0,1,tier1,store,11,1,1,12626.26
4,3,2021,4,128,6.59,5336,44,0,1,74505,...,0,0,0,0,tier3,store,24,1,1,20662.25

In [79]:
df["city_tier"].unique()  # Display the unique values in the "city_tier" column

<StringArray>
['tier1', 'tier3', 'tier2']
Length: 3, dtype: str

In [80]:
city_tier_to_nums = {
    "tier1": 0,
    "tier2": 1,
    "tier3": 2
}

df["city_tier"] = df["city_tier"].map(city_tier_to_nums)  # Map the city tiers to numerical values using the dictionary

In [81]:
df.head(5)  # Display the first 5 rows of the DataFrame

,brand,release_year,ram_gb,storage_gb,screen_size_inches,battery_capacity,camera_score,os_type,has_5g,original_price,...,screen_cracked,body_damage,repair_history,water_damage,city_tier,seller_type,warranty_remaining_months,box_available,charger_available,resale_price
0,0,2025,4,256,6.93,4130,100,0,1,147337,...,0,0,0,0,0,individual,11,1,1,47891.46
1,1,2024,16,64,6.29,5558,67,0,1,75725,...,0,0,0,0,2,store,8,1,0,17663.21
2,2,2022,4,128,5.52,5945,67,1,1,134358,...,0,0,0,0,0,individual,0,0,1,67268.20
3,3,2024,16,512,5.99,5767,57,0,1,96807,...,0,0,0,1,0,store,11,1,1,12626.26
4,3,2021,4,128,6.59,5336,44,0,1,74505,...,0,0,0,0,2,store,24,1,1,20662.25

In [82]:
df["seller_type"].unique()  # Display the unique values in the "seller_type" column

<StringArray>
['individual', 'store']
Length: 2, dtype: str

In [83]:
df["seller_type"].isna().sum()  # Count the number of missing values in the "seller_type" column

np.int64(0)

In [84]:
seller_type_to_nums = {
    "individual": 0,
    "store": 1
}

df["seller_type"] = df["seller_type"].map(seller_type_to_nums)  # Map the seller types to numerical values using the dictionary

In [85]:
df.head(5)  # Display the first 5 rows of the DataFrame

,brand,release_year,ram_gb,storage_gb,screen_size_inches,battery_capacity,camera_score,os_type,has_5g,original_price,...,screen_cracked,body_damage,repair_history,water_damage,city_tier,seller_type,warranty_remaining_months,box_available,charger_available,resale_price
0,0,2025,4,256,6.93,4130,100,0,1,147337,...,0,0,0,0,0,0,11,1,1,47891.46
1,1,2024,16,64,6.29,5558,67,0,1,75725,...,0,0,0,0,2,1,8,1,0,17663.21
2,2,2022,4,128,5.52,5945,67,1,1,134358,...,0,0,0,0,0,0,0,0,1,67268.20
3,3,2024,16,512,5.99,5767,57,0,1,96807,...,0,0,0,1,0,1,11,1,1,12626.26
4,3,2021,4,128,6.59,5336,44,0,1,74505,...,0,0,0,0,2,1,24,1,1,20662.25

In [86]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 25 columns):
 #   Column                     Non-Null Count    Dtype
---  ------                     --------------    -----
 0   brand                      1000000 non-null  int64
 1   release_year               1000000 non-null  int64
 2   ram_gb                     1000000 non-null  int64
 3   storage_gb                 1000000 non-null  int64
 4   screen_size_inches         1000000 non-null  float64
 5   battery_capacity           1000000 non-null  int64
 6   camera_score               1000000 non-null  int64
 7   os_type                    1000000 non-null  int64
 8   has_5g                     1000000 non-null  int64
 9   original_price             1000000 non-null  int64
 10  purchase_year              1000000 non-null  int64
 11  age_months                 1000000 non-null  int64
 12  usage_hours_per_day        1000000 non-null  float64
 13  condition                  1000000 non-null  str
 14  battery_health             1000000 non-null  int64
 15  screen_cracked             1000000 non-null  int64
 16  body_damage                1000000 non-null  int64
 17  repair_history             1000000 non-null  int64
 18  water_damage               1000000 non-null  int64
 19  city_tier                  1000000 non-null  int64
 20  seller_type                1000000 non-null  int64
 21  warranty_remaining_months  1000000 non-null  int64
 22  box_available              1000000 non-null  int64
 23  charger_available          1000000 non-null  int64
 24  resale_price               1000000 non-null  float64
dtypes: float64(3), int64(21), str(1)
memory usage: 190.7 MB

In [87]:
df["condition"].unique()  # Display the unique values in the "condition" column

<StringArray>
['excellent', 'fair', 'good', 'poor']
Length: 4, dtype: str

In [88]:
# ['excellent', 'fair', 'good', 'poor']
condition_to_nums = {
    "excellent": 0,
    "fair": 1,
    "good": 2,
    "poor": 3
}

df["condition"] = df["condition"].map(condition_to_nums)  # Map the condition values to numerical values using the dictionary

In [89]:
df.head(5)

,brand,release_year,ram_gb,storage_gb,screen_size_inches,battery_capacity,camera_score,os_type,has_5g,original_price,...,screen_cracked,body_damage,repair_history,water_damage,city_tier,seller_type,warranty_remaining_months,box_available,charger_available,resale_price
0,0,2025,4,256,6.93,4130,100,0,1,147337,...,0,0,0,0,0,0,11,1,1,47891.46
1,1,2024,16,64,6.29,5558,67,0,1,75725,...,0,0,0,0,2,1,8,1,0,17663.21
2,2,2022,4,128,5.52,5945,67,1,1,134358,...,0,0,0,0,0,0,0,0,1,67268.20
3,3,2024,16,512,5.99,5767,57,0,1,96807,...,0,0,0,1,0,1,11,1,1,12626.26
4,3,2021,4,128,6.59,5336,44,0,1,74505,...,0,0,0,0,2,1,24,1,1,20662.25

In [91]:
df.info()  # Display information about the DataFrame

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 25 columns):
 #   Column                     Non-Null Count    Dtype
---  ------                     --------------    -----
 0   brand                      1000000 non-null  int64
 1   release_year               1000000 non-null  int64
 2   ram_gb                     1000000 non-null  int64
 3   storage_gb                 1000000 non-null  int64
 4   screen_size_inches         1000000 non-null  float64
 5   battery_capacity           1000000 non-null  int64
 6   camera_score               1000000 non-null  int64
 7   os_type                    1000000 non-null  int64
 8   has_5g                     1000000 non-null  int64
 9   original_price             1000000 non-null  int64
 10  purchase_year              1000000 non-null  int64
 11  age_months                 1000000 non-null  int64
 12  usage_hours_per_day        1000000 non-null  float64
 13  condition                  1000000 non-null  int64
 14  battery_health             1000000 non-null  int64
 15  screen_cracked             1000000 non-null  int64
 16  body_damage                1000000 non-null  int64
 17  repair_history             1000000 non-null  int64
 18  water_damage               1000000 non-null  int64
 19  city_tier                  1000000 non-null  int64
 20  seller_type                1000000 non-null  int64
 21  warranty_remaining_months  1000000 non-null  int64
 22  box_available              1000000 non-null  int64
 23  charger_available          1000000 non-null  int64
 24  resale_price               1000000 non-null  float64
dtypes: float64(3), int64(22)
memory usage: 190.7 MB

In [92]:
df.to_csv("used_phone_price_prediction_cleaned.csv", index=False)  # Save the cleaned DataFrame to a new CSV file without the index